In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
# Define file paths
#读取带有三种奖牌数以及对应年份的数据
csv_file_path = 'summerOly_athletes.csv'
#读取每一年相对应的运动discipline类型，event、sport、discipline总数
# 读取 CSV 文件
csv_data = pd.read_csv(csv_file_path)  # 读取CSV文件
# 打印前五行的内容
csv_data.head()

Name Sex            Team  NOC  Year         City  \
0              A Dijiang   M           China  CHN  1992    Barcelona   
1               A Lamusi   M           China  CHN  2012       London   
2            Gunnar Aaby   M         Denmark  DEN  1920    Antwerpen   
3            Edgar Aabye   M  Denmark/Sweden  DEN  1900        Paris   
4  Cornelia (-strannood)   F     Netherlands  NED  1932  Los Angeles   

        Sport                         Event     Medal  
0  Basketball   Basketball Men's Basketball  No medal  
1        Judo  Judo Men's Extra-Lightweight  No medal  
2    Football       Football Men's Football  No medal  
3  Tug-Of-War   Tug-Of-War Men's Tug-Of-War      Gold  
4   Athletics  Athletics Women's 100 metres  No medal

In [2]:
df = pd.read_csv(csv_file_path)
# 提取某一列数据（例如 'ColumnName' 列）
column_data = df["NOC"]  # 替换为你的列名
# 将列数据转换为集合
countries = set(column_data)
# 输出集合
print(countries)
num_of_countries=len(countries)
print(num_of_countries)

{'SGP', 'BEN', 'CRO', 'MLT', 'OMA', 'DEN', 'THA', 'MOZ', 'GDR', 'SCG', 'NFL', 'ROC', 'TCH', 'MNE', 'DMA', 'UNK', 'CAM', 'ROT', 'TLS', 'KEN', 'ARG', 'DOM', 'SKN', 'FIN', 'BIZ', 'HKG', 'GRE', 'CAY', 'ERI', 'VEN', 'YEM', 'ZAM', 'UGA', 'SRI', 'AIN', 'ANT', 'ECU', 'CZE', 'BOT', 'BHU', 'VIN', 'ARU', 'AFG', 'NAM', 'IVB', 'MLI', 'AZE', 'PRK', 'GEO', 'FRG', 'BLR', 'TAN', 'POR', 'TUN', 'MGL', 'LAT', 'MAL', 'LCA', 'FSM', 'NRU', 'SEN', 'CGO', 'IRI', 'LBR', 'BIH', 'BOL', 'COD', 'SWZ', 'NBO', 'GER', 'MKD', 'KUW', 'CHN', 'MTN', 'IND', 'CHA', 'VAN', 'TUV', 'SRB', 'ESP', 'MAD', 'SOM', 'COK', 'ARM', 'IRQ', 'SAA', 'SVK', 'BAH', 'AHO', 'AUS', 'BEL', 'BRU', 'SEY', 'TKM', 'GBS', 'KSA', 'GBR', 'NEP', 'CIV', 'MAW', 'RHO', 'USA', 'RSA', 'MYA', 'BUL', 'LTU', 'BAN', 'URS', 'AND', 'VIE', 'STP', 'PAR', 'BRA', 'CPV', 'MDV', 'PLE', 'ZIM', 'QAT', 'JOR', 'ANZ', 'UKR', 'SMR', 'ALG', 'ISV', 'HUN', 'YUG', 'KAZ', 'SUD', 'ISR', 'FIJ', 'COM', 'PAK', 'ESA', 'LAO', 'SAM', 'MHL', 'VNM', 'EST', 'SUI', 'ETH', 'SSD', 'LES', 'ROU'

In [3]:
# 提取某一列数据（例如 'ColumnName' 列）
column_data = df["Event"]  # 替换为你的列名
# 将列数据转换为集合
unique_elements_of_event = set(column_data)
# 输出集合
print(unique_elements_of_event)
print("不同event的数量:", len(unique_elements_of_event))
# 将集合转换为列表并排序
sorted_unique_events = sorted(unique_elements_of_event)

# 输出排序后的列表
print("排序后的 Event 列表:", sorted_unique_events)
print("不同 Event 的数量:", len(sorted_unique_events))


{"Tennis Men's Singles, Covered Courts", "Women's Kayak Four 500m Team", "Boxing Men's Featherweight", "Men's Pair Team", "Canoeing Men's Canadian Doubles, 500 metres", "Women's 60kg", "Fencing Men's Sabre, Masters, Individual", "Cycling Men's Omnium", "Women's Four Team", 'Relay Only Athlete', "Men's 4 x 200m Freestyle Relay", "Equestrianism Men's Jumping, Individual", "Archery Men's Team", "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 metres, Team", "Equestrianism Men's Three-Day Event, Team", "Athletics Women's 100 metres Hurdles", "Men's Kumite -67kg", "Cycling Men's 100 kilometres", "Shooting Men's Dueling Pistol Au Commandement, 25 metres", "Archery Men's Au Cordon Dore, 50 metres", '25m Pistol Women', "Gymnastics Men's Horse Vault", "Rowing Men's Coxed Eights", "Gymnastics Men's Parallel Bars", "Lightweight Men's Double Sculls Team", 'Men -90 kg', "Women's Sabre Team", "Lightweight Women's Double Sculls", "Table Tennis Women's Singles", 'Sailing Mixed One Person Ding

In [4]:
# 提取某一列数据（例如 'ColumnName' 列）
column_data = df["Year"]  # 替换为你的列名
# 将列数据转换为集合
unique_elements_of_year = set(column_data)
# 将集合转换为列表并排序
sorted_unique_years = sorted(unique_elements_of_year)

# 输出排序后的列表
print("排序后的年份列表:", sorted_unique_years)
print("不同年份的数量:", len(sorted_unique_years))
# 删除 1906
if 1906 in sorted_unique_years:
    sorted_unique_years.remove(1906)

# 输出删除后的列表
print("删除 1906 后的年份列表:", sorted_unique_years)
print("不同年份的数量:", len(sorted_unique_years))


排序后的年份列表: [1896, 1900, 1904, 1906, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024]
不同年份的数量: 31
删除 1906 后的年份列表: [1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024]
不同年份的数量: 30


In [5]:
import numpy as np

zero_matrix = np.zeros((len(sorted_unique_years),  len(unique_elements_of_event)))
print(zero_matrix)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
import pandas as pd
# 指定行名和列名
row_names = ["Year1", "Year2", "Year3"]  # 替换为你的行名列表
column_names = ["Event1", "Event2", "Event3"]  # 替换为你的列名列表

# 遍历集合中的每个字符串元素
for file_name in countries:
    # 创建一个 DataFrame，初始值为 0，并指定行名和列名
    df = pd.DataFrame(0, index=sorted_unique_years, columns=sorted_unique_events)

    # 保存为 Excel 文件
    output_file = f"{file_name}.xlsx"  # 文件名
    df.to_excel(output_file, index=True, header=True)  # 保留行名和列名

    print(f"已创建文件: {output_file}")

已创建文件: SGP.xlsx
已创建文件: BEN.xlsx
已创建文件: CRO.xlsx
已创建文件: MLT.xlsx
已创建文件: OMA.xlsx
已创建文件: DEN.xlsx
已创建文件: THA.xlsx
已创建文件: MOZ.xlsx
已创建文件: GDR.xlsx
已创建文件: SCG.xlsx
已创建文件: NFL.xlsx
已创建文件: ROC.xlsx
已创建文件: TCH.xlsx
已创建文件: MNE.xlsx
已创建文件: DMA.xlsx
已创建文件: UNK.xlsx
已创建文件: CAM.xlsx
已创建文件: ROT.xlsx
已创建文件: TLS.xlsx
已创建文件: KEN.xlsx
已创建文件: ARG.xlsx
已创建文件: DOM.xlsx
已创建文件: SKN.xlsx
已创建文件: FIN.xlsx
已创建文件: BIZ.xlsx
已创建文件: HKG.xlsx
已创建文件: GRE.xlsx
已创建文件: CAY.xlsx
已创建文件: ERI.xlsx
已创建文件: VEN.xlsx
已创建文件: YEM.xlsx
已创建文件: ZAM.xlsx
已创建文件: UGA.xlsx
已创建文件: SRI.xlsx
已创建文件: AIN.xlsx
已创建文件: ANT.xlsx
已创建文件: ECU.xlsx
已创建文件: CZE.xlsx
已创建文件: BOT.xlsx
已创建文件: BHU.xlsx
已创建文件: VIN.xlsx
已创建文件: ARU.xlsx
已创建文件: AFG.xlsx
已创建文件: NAM.xlsx
已创建文件: IVB.xlsx
已创建文件: MLI.xlsx
已创建文件: AZE.xlsx
已创建文件: PRK.xlsx
已创建文件: GEO.xlsx
已创建文件: FRG.xlsx
已创建文件: BLR.xlsx
已创建文件: TAN.xlsx
已创建文件: POR.xlsx
已创建文件: TUN.xlsx
已创建文件: MGL.xlsx
已创建文件: LAT.xlsx
已创建文件: MAL.xlsx
已创建文件: LCA.xlsx
已创建文件: FSM.xlsx
已创建文件: NRU.xlsx
已创建文件: SEN.xlsx
已创建文件: CGO.xlsx
已创建文件: I

In [7]:
import pandas as pd
import os

# 读取 CSV 文件
file_path = "summerOly_athletes.csv"  # 替换为你的 CSV 文件路径
df = pd.read_csv(file_path)

# 定义列名
columns = ["NOC", "Year", "Event"]  # 替换为你的列名

# 检查列名是否有效
if all(col in df.columns for col in columns):
    # 遍历每一行
    for i in range(len(df)):
        # 提取第 i 行的指定列的值
        row_values = df.loc[i, columns].tolist()  # 转换为列表
        print(f"第 {i} 行的 {columns} 列的值:", row_values)

        # 获取 NOC 名称
        noc_name = row_values[0]  # NOC 列的值
        year = row_values[1]  # Year 列的值
        event = row_values[2]  # Event 列的值

        # 构造对应的 Excel 文件名
        excel_file = f"{noc_name}.xlsx"

        # 检查 Excel 文件是否存在
        if os.path.exists(excel_file):
            # 读取 Excel 文件
            df_excel = pd.read_excel(excel_file, index_col=0)  # 假设第一列是行名

            # 检查 Year 行和 Event 列是否存在
            if year in df_excel.index and event in df_excel.columns:
                # 对指定位置的数据加 1
                df_excel.loc[year, event] += 1

                # 保存修改后的 Excel 文件
                df_excel.to_excel(excel_file)
                print(f"文件 {excel_file} 的 {year} 行 {event} 列数据已加 1。")
            else:
                print(f"文件 {excel_file} 中不存在 {year} 行或 {event} 列。")
        else:
            print(f"文件 {excel_file} 不存在。")
else:
    print("列名无效，请检查输入。")

第 0 行的 ['NOC', 'Year', 'Event'] 列的值: ['CHN', 1992, "Basketball Men's Basketball"]
文件 CHN.xlsx 的 1992 行 Basketball Men's Basketball 列数据已加 1。
第 1 行的 ['NOC', 'Year', 'Event'] 列的值: ['CHN', 2012, "Judo Men's Extra-Lightweight"]
文件 CHN.xlsx 的 2012 行 Judo Men's Extra-Lightweight 列数据已加 1。
第 2 行的 ['NOC', 'Year', 'Event'] 列的值: ['DEN', 1920, "Football Men's Football"]
文件 DEN.xlsx 的 1920 行 Football Men's Football 列数据已加 1。
第 3 行的 ['NOC', 'Year', 'Event'] 列的值: ['DEN', 1900, "Tug-Of-War Men's Tug-Of-War"]
文件 DEN.xlsx 的 1900 行 Tug-Of-War Men's Tug-Of-War 列数据已加 1。
第 4 行的 ['NOC', 'Year', 'Event'] 列的值: ['NED', 1932, "Athletics Women's 100 metres"]
文件 NED.xlsx 的 1932 行 Athletics Women's 100 metres 列数据已加 1。
第 5 行的 ['NOC', 'Year', 'Event'] 列的值: ['NED', 1932, "Athletics Women's 4 x 100 metres Relay"]
文件 NED.xlsx 的 1932 行 Athletics Women's 4 x 100 metres Relay 列数据已加 1。
第 6 行的 ['NOC', 'Year', 'Event'] 列的值: ['FIN', 1952, "Swimming Men's 400 metres Freestyle"]
文件 FIN.xlsx 的 1952 行 Swimming Men's 400 metres Frees

文件 NOR.xlsx 的 1996 行 Football Women's Football 列数据已加 1。
第 55 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1920, "Gymnastics Men's Team All-Around, Free System"]
文件 NOR.xlsx 的 1920 行 Gymnastics Men's Team All-Around, Free System 列数据已加 1。
第 56 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1912, "Fencing Men's Foil, Individual"]
文件 NOR.xlsx 的 1912 行 Fencing Men's Foil, Individual 列数据已加 1。
第 57 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1912, "Fencing Men's epee, Individual"]
文件 NOR.xlsx 的 1912 行 Fencing Men's epee, Individual 列数据已加 1。
第 58 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1912, "Fencing Men's epee, Team"]
文件 NOR.xlsx 的 1912 行 Fencing Men's epee, Team 列数据已加 1。
第 59 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1920, "Football Men's Football"]
文件 NOR.xlsx 的 1920 行 Football Men's Football 列数据已加 1。
第 60 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1912, 'Sailing Mixed 8 metres']
文件 NOR.xlsx 的 1912 行 Sailing Mixed 8 metres 列数据已加 1。
第 61 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1992, 'Equestrianism Mixed J

文件 BLR.xlsx 的 2008 行 Canoeing Men's Kayak Fours, 1,000 metres 列数据已加 1。
第 111 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2008, "Handball Men's Handball"]
文件 FRA.xlsx 的 2008 行 Handball Men's Handball 列数据已加 1。
第 112 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2012, "Handball Men's Handball"]
文件 FRA.xlsx 的 2012 行 Handball Men's Handball 列数据已加 1。
第 113 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2016, "Handball Men's Handball"]
文件 FRA.xlsx 的 2016 行 Handball Men's Handball 列数据已加 1。
第 114 行的 ['NOC', 'Year', 'Event'] 列的值: ['ARG', 2012, "Rowing Women's Coxless Pairs"]
文件 ARG.xlsx 的 2012 行 Rowing Women's Coxless Pairs 列数据已加 1。
第 115 行的 ['NOC', 'Year', 'Event'] 列的值: ['GRE', 2004, "Fencing Men's epee, Individual"]
文件 GRE.xlsx 的 2004 行 Fencing Men's epee, Individual 列数据已加 1。
第 116 行的 ['NOC', 'Year', 'Event'] 列的值: ['CMR', 2000, "Football Men's Football"]
文件 CMR.xlsx 的 2000 行 Football Men's Football 列数据已加 1。
第 117 行的 ['NOC', 'Year', 'Event'] 列的值: ['CMR', 1968, "Boxing Men's Middleweight"]
文件 CMR.xlsx 的 1968 

文件 KUW.xlsx 的 1976 行 Athletics Men's 4 x 100 metres Relay 列数据已加 1。
第 169 行的 ['NOC', 'Year', 'Event'] 列的值: ['KUW', 1980, "Athletics Men's 400 metres Hurdles"]
文件 KUW.xlsx 的 1980 行 Athletics Men's 400 metres Hurdles 列数据已加 1。
第 170 行的 ['NOC', 'Year', 'Event'] 列的值: ['BRN', 2016, "Athletics Men's 400 metres"]
文件 BRN.xlsx 的 2016 行 Athletics Men's 400 metres 列数据已加 1。
第 171 行的 ['NOC', 'Year', 'Event'] 列的值: ['PAK', 1996, "Athletics Men's Hammer Throw"]
文件 PAK.xlsx 的 1996 行 Athletics Men's Hammer Throw 列数据已加 1。
第 172 行的 ['NOC', 'Year', 'Event'] 列的值: ['IRQ', 1964, "Weightlifting Men's Lightweight"]
文件 IRQ.xlsx 的 1964 行 Weightlifting Men's Lightweight 列数据已加 1。
第 173 行的 ['NOC', 'Year', 'Event'] 列的值: ['IRQ', 2004, "Football Men's Football"]
文件 IRQ.xlsx 的 2004 行 Football Men's Football 列数据已加 1。
第 174 行的 ['NOC', 'Year', 'Event'] 列的值: ['KUW', 1980, "Athletics Men's Long Jump"]
文件 KUW.xlsx 的 1980 行 Athletics Men's Long Jump 列数据已加 1。
第 175 行的 ['NOC', 'Year', 'Event'] 列的值: ['PAK', 1992, "Athletics Men's 4

文件 EGY.xlsx 的 2008 行 Handball Men's Handball 列数据已加 1。
第 225 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2008, "Taekwondo Women's Heavyweight"]
文件 EGY.xlsx 的 2008 行 Taekwondo Women's Heavyweight 列数据已加 1。
第 226 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2008, "Synchronized Swimming Women's Duet"]
文件 EGY.xlsx 的 2008 行 Synchronized Swimming Women's Duet 列数据已加 1。
第 227 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2008, "Synchronized Swimming Women's Team"]
文件 EGY.xlsx 的 2008 行 Synchronized Swimming Women's Team 列数据已加 1。
第 228 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2012, "Synchronized Swimming Women's Team"]
文件 EGY.xlsx 的 2012 行 Synchronized Swimming Women's Team 列数据已加 1。
第 229 行的 ['NOC', 'Year', 'Event'] 列的值: ['ERI', 2008, "Athletics Men's 5,000 metres"]
文件 ERI.xlsx 的 2008 行 Athletics Men's 5,000 metres 列数据已加 1。
第 230 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Volleyball Men's Volleyball"]
文件 EGY.xlsx 的 2016 行 Volleyball Men's Volleyball 列数据已加 1。
第 231 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY',

文件 EGY.xlsx 的 1952 行 Water Polo Men's Water Polo 列数据已加 1。
第 282 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1952, "Swimming Men's 100 metres Freestyle"]
文件 EGY.xlsx 的 1952 行 Swimming Men's 100 metres Freestyle 列数据已加 1。
第 283 行的 ['NOC', 'Year', 'Event'] 列的值: ['UAR', 1960, "Water Polo Men's Water Polo"]
文件 UAR.xlsx 的 1960 行 Water Polo Men's Water Polo 列数据已加 1。
第 284 行的 ['NOC', 'Year', 'Event'] 列的值: ['UAR', 1960, "Athletics Men's 100 metres"]
文件 UAR.xlsx 的 1960 行 Athletics Men's 100 metres 列数据已加 1。
第 285 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1952, "Weightlifting Men's Light-Heavyweight"]
文件 EGY.xlsx 的 1952 行 Weightlifting Men's Light-Heavyweight 列数据已加 1。
第 286 行的 ['NOC', 'Year', 'Event'] 列的值: ['UAR', 1960, "Weightlifting Men's Light-Heavyweight"]
文件 UAR.xlsx 的 1960 行 Weightlifting Men's Light-Heavyweight 列数据已加 1。
第 287 行的 ['NOC', 'Year', 'Event'] 列的值: ['TUN', 1976, "Handball Men's Handball"]
文件 TUN.xlsx 的 1976 行 Handball Men's Handball 列数据已加 1。
第 288 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY

文件 EGY.xlsx 的 2008 行 Shooting Women's Air Rifle, 10 metres 列数据已加 1。
第 339 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Shooting Women's Air Rifle, 10 metres"]
文件 EGY.xlsx 的 2016 行 Shooting Women's Air Rifle, 10 metres 列数据已加 1。
第 340 行的 ['NOC', 'Year', 'Event'] 列的值: ['SUD', 1972, "Football Men's Football"]
文件 SUD.xlsx 的 1972 行 Football Men's Football 列数据已加 1。
第 341 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Volleyball Men's Volleyball"]
文件 EGY.xlsx 的 2016 行 Volleyball Men's Volleyball 列数据已加 1。
第 342 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Boxing Men's Lightweight"]
文件 EGY.xlsx 的 2016 行 Boxing Men's Lightweight 列数据已加 1。
第 343 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Judo Men's Half-Middleweight"]
文件 EGY.xlsx 的 2016 行 Judo Men's Half-Middleweight 列数据已加 1。
第 344 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1948, "Gymnastics Men's Individual All-Around"]
文件 EGY.xlsx 的 1948 行 Gymnastics Men's Individual All-Around 列数据已加 1。
第 345 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 194

文件 EGY.xlsx 的 1936 行 Fencing Men's Foil, Team 列数据已加 1。
第 394 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1936, "Fencing Men's epee, Individual"]
文件 EGY.xlsx 的 1936 行 Fencing Men's epee, Individual 列数据已加 1。
第 395 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1936, "Fencing Men's epee, Team"]
文件 EGY.xlsx 的 1936 行 Fencing Men's epee, Team 列数据已加 1。
第 396 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1948, "Fencing Men's Foil, Team"]
文件 EGY.xlsx 的 1948 行 Fencing Men's Foil, Team 列数据已加 1。
第 397 行的 ['NOC', 'Year', 'Event'] 列的值: ['USA', 2000, "Athletics Men's 10,000 metres"]
文件 USA.xlsx 的 2000 行 Athletics Men's 10,000 metres 列数据已加 1。
第 398 行的 ['NOC', 'Year', 'Event'] 列的值: ['USA', 2004, "Athletics Men's 10,000 metres"]
文件 USA.xlsx 的 2004 行 Athletics Men's 10,000 metres 列数据已加 1。
第 399 行的 ['NOC', 'Year', 'Event'] 列的值: ['USA', 2008, "Athletics Men's 10,000 metres"]
文件 USA.xlsx 的 2008 行 Athletics Men's 10,000 metres 列数据已加 1。
第 400 行的 ['NOC', 'Year', 'Event'] 列的值: ['USA', 2012, "Athletics Men's Marathon"]
文件 USA

文件 KSA.xlsx 的 1984 行 Football Men's Football 列数据已加 1。
第 450 行的 ['NOC', 'Year', 'Event'] 列的值: ['IRI', 1976, "Water Polo Men's Water Polo"]
文件 IRI.xlsx 的 1976 行 Water Polo Men's Water Polo 列数据已加 1。
第 451 行的 ['NOC', 'Year', 'Event'] 列的值: ['JOR', 1984, "Shooting Men's Small-Bore Rifle, Three Positions, 50 metres"]
文件 JOR.xlsx 的 1984 行 Shooting Men's Small-Bore Rifle, Three Positions, 50 metres 列数据已加 1。
第 452 行的 ['NOC', 'Year', 'Event'] 列的值: ['BRN', 1984, "Shooting Men's Rapid-Fire Pistol, 25 metres"]
文件 BRN.xlsx 的 1984 行 Shooting Men's Rapid-Fire Pistol, 25 metres 列数据已加 1。
第 453 行的 ['NOC', 'Year', 'Event'] 列的值: ['ETH', 1972, "Cycling Men's Road Race, Individual"]
文件 ETH.xlsx 的 1972 行 Cycling Men's Road Race, Individual 列数据已加 1。
第 454 行的 ['NOC', 'Year', 'Event'] 列的值: ['MAS', 1968, "Athletics Men's 400 metres Hurdles"]
文件 MAS.xlsx 的 1968 行 Athletics Men's 400 metres Hurdles 列数据已加 1。
第 455 行的 ['NOC', 'Year', 'Event'] 列的值: ['PAK', 1960, "Hockey Men's Hockey"]
文件 PAK.xlsx 的 1960 行 Hockey Men's 

文件 EGY.xlsx 的 1920 行 Football Men's Football 列数据已加 1。
第 505 行的 ['NOC', 'Year', 'Event'] 列的值: ['MAS', 1996, "Swimming Men's 200 metres Individual Medley"]
文件 MAS.xlsx 的 1996 行 Swimming Men's 200 metres Individual Medley 列数据已加 1。
第 506 行的 ['NOC', 'Year', 'Event'] 列的值: ['MAS', 1996, "Swimming Men's 400 metres Individual Medley"]
文件 MAS.xlsx 的 1996 行 Swimming Men's 400 metres Individual Medley 列数据已加 1。
第 507 行的 ['NOC', 'Year', 'Event'] 列的值: ['MAS', 1996, "Swimming Men's 4 x 100 metres Medley Relay"]
文件 MAS.xlsx 的 1996 行 Swimming Men's 4 x 100 metres Medley Relay 列数据已加 1。
第 508 行的 ['NOC', 'Year', 'Event'] 列的值: ['MAS', 2000, "Swimming Men's 400 metres Individual Medley"]
文件 MAS.xlsx 的 2000 行 Swimming Men's 400 metres Individual Medley 列数据已加 1。
第 509 行的 ['NOC', 'Year', 'Event'] 列的值: ['SGP', 1992, "Badminton Women's Singles"]
文件 SGP.xlsx 的 1992 行 Badminton Women's Singles 列数据已加 1。
第 510 行的 ['NOC', 'Year', 'Event'] 列的值: ['SGP', 1996, "Badminton Women's Singles"]
文件 SGP.xlsx 的 1996 行 Badminton W

文件 JPN.xlsx 的 1992 行 Fencing Men's Foil, Individual 列数据已加 1。
第 559 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1972, "Wrestling Men's Featherweight, Freestyle"]
文件 JPN.xlsx 的 1972 行 Wrestling Men's Featherweight, Freestyle 列数据已加 1。
第 560 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1968, "Athletics Men's 4 x 100 metres Relay"]
文件 JPN.xlsx 的 1968 行 Athletics Men's 4 x 100 metres Relay 列数据已加 1。
第 561 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1968, "Athletics Men's Long Jump"]
文件 JPN.xlsx 的 1968 行 Athletics Men's Long Jump 列数据已加 1。
第 562 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1936, "Rowing Men's Coxed Pairs"]
文件 JPN.xlsx 的 1936 行 Rowing Men's Coxed Pairs 列数据已加 1。
第 563 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1972, "Basketball Men's Basketball"]
文件 JPN.xlsx 的 1972 行 Basketball Men's Basketball 列数据已加 1。
第 564 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 1976, "Basketball Men's Basketball"]
文件 JPN.xlsx 的 1976 行 Basketball Men's Basketball 列数据已加 1。
第 565 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 2000, 

文件 MON.xlsx 的 1936 行 Shooting Men's Rapid-Fire Pistol, 25 metres 列数据已加 1。
第 614 行的 ['NOC', 'Year', 'Event'] 列的值: ['MON', 1936, "Shooting Men's Small-Bore Rifle, Prone, 50 metres"]
文件 MON.xlsx 的 1936 行 Shooting Men's Small-Bore Rifle, Prone, 50 metres 列数据已加 1。
第 615 行的 ['NOC', 'Year', 'Event'] 列的值: ['MON', 1948, "Shooting Men's Small-Bore Rifle, Prone, 50 metres"]
文件 MON.xlsx 的 1948 行 Shooting Men's Small-Bore Rifle, Prone, 50 metres 列数据已加 1。
第 616 行的 ['NOC', 'Year', 'Event'] 列的值: ['MON', 1952, "Shooting Men's Small-Bore Rifle, Three Positions, 50 metres"]
文件 MON.xlsx 的 1952 行 Shooting Men's Small-Bore Rifle, Three Positions, 50 metres 列数据已加 1。
第 617 行的 ['NOC', 'Year', 'Event'] 列的值: ['MON', 1952, "Shooting Men's Small-Bore Rifle, Prone, 50 metres"]
文件 MON.xlsx 的 1952 行 Shooting Men's Small-Bore Rifle, Prone, 50 metres 列数据已加 1。
第 618 行的 ['NOC', 'Year', 'Event'] 列的值: ['NOR', 1920, 'Sailing Mixed 7 metres']
文件 NOR.xlsx 的 1920 行 Sailing Mixed 7 metres 列数据已加 1。
第 619 行的 ['NOC', 'Year', 'Even

文件 FRA.xlsx 的 1984 行 Shooting Men's Running Target, 50 metres 列数据已加 1。
第 669 行的 ['NOC', 'Year', 'Event'] 列的值: ['GDR', 1988, "Diving Women's Platform"]
文件 GDR.xlsx 的 1988 行 Diving Women's Platform 列数据已加 1。
第 670 行的 ['NOC', 'Year', 'Event'] 列的值: ['TUN', 1988, "Football Men's Football"]
文件 TUN.xlsx 的 1988 行 Football Men's Football 列数据已加 1。
第 671 行的 ['NOC', 'Year', 'Event'] 列的值: ['IRQ', 1988, "Football Men's Football"]
文件 IRQ.xlsx 的 1988 行 Football Men's Football 列数据已加 1。
第 672 行的 ['NOC', 'Year', 'Event'] 列的值: ['NGR', 1972, "Athletics Men's 800 metres"]
文件 NGR.xlsx 的 1972 行 Athletics Men's 800 metres 列数据已加 1。
第 673 行的 ['NOC', 'Year', 'Event'] 列的值: ['NGR', 1972, "Athletics Men's 1,500 metres"]
文件 NGR.xlsx 的 1972 行 Athletics Men's 1,500 metres 列数据已加 1。
第 674 行的 ['NOC', 'Year', 'Event'] 列的值: ['KAZ', 2008, "Judo Women's Half-Heavyweight"]
文件 KAZ.xlsx 的 2008 行 Judo Women's Half-Heavyweight 列数据已加 1。
第 675 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 2008, "Athletics Men's 4 x 400 metres Relay"]
文件 J

文件 LIB.xlsx 的 1972 行 Cycling Men's Individual Pursuit, 4,000 metres 列数据已加 1。
第 724 行的 ['NOC', 'Year', 'Event'] 列的值: ['LIB', 1972, "Wrestling Men's Welterweight, Freestyle"]
文件 LIB.xlsx 的 1972 行 Wrestling Men's Welterweight, Freestyle 列数据已加 1。
第 725 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2000, "Volleyball Men's Volleyball"]
文件 EGY.xlsx 的 2000 行 Volleyball Men's Volleyball 列数据已加 1。
第 726 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2008, "Volleyball Men's Volleyball"]
文件 EGY.xlsx 的 2008 行 Volleyball Men's Volleyball 列数据已加 1。
第 727 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2016, "Volleyball Men's Volleyball"]
文件 EGY.xlsx 的 2016 行 Volleyball Men's Volleyball 列数据已加 1。
第 728 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1952, "Water Polo Men's Water Polo"]
文件 EGY.xlsx 的 1952 行 Water Polo Men's Water Polo 列数据已加 1。
第 729 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 2000, "Handball Men's Handball"]
文件 EGY.xlsx 的 2000 行 Handball Men's Handball 列数据已加 1。
第 730 行的 ['NOC', 'Year', 'Event'] 列的值: ['EGY', 1984, "B

文件 HUN.xlsx 的 1992 行 Canoeing Men's Kayak Fours, 1,000 metres 列数据已加 1。
第 782 行的 ['NOC', 'Year', 'Event'] 列的值: ['GER', 1906, "Gymnastics Men's Team All-Around"]
文件 GER.xlsx 中不存在 1906 行或 Gymnastics Men's Team All-Around 列。
第 783 行的 ['NOC', 'Year', 'Event'] 列的值: ['GBR', 1976, "Swimming Men's 100 metres Backstroke"]
文件 GBR.xlsx 的 1976 行 Swimming Men's 100 metres Backstroke 列数据已加 1。
第 784 行的 ['NOC', 'Year', 'Event'] 列的值: ['GBR', 1976, "Swimming Men's 4 x 100 metres Medley Relay"]
文件 GBR.xlsx 的 1976 行 Swimming Men's 4 x 100 metres Medley Relay 列数据已加 1。
第 785 行的 ['NOC', 'Year', 'Event'] 列的值: ['GBR', 1980, "Swimming Men's 100 metres Backstroke"]
文件 GBR.xlsx 的 1980 行 Swimming Men's 100 metres Backstroke 列数据已加 1。
第 786 行的 ['NOC', 'Year', 'Event'] 列的值: ['GBR', 1980, "Swimming Men's 100 metres Butterfly"]
文件 GBR.xlsx 的 1980 行 Swimming Men's 100 metres Butterfly 列数据已加 1。
第 787 行的 ['NOC', 'Year', 'Event'] 列的值: ['GBR', 1980, "Swimming Men's 4 x 100 metres Medley Relay"]
文件 GBR.xlsx 的 1980 行 Swimming 

文件 URS.xlsx 的 1988 行 Swimming Women's 50 metres Freestyle 列数据已加 1。
第 838 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1988, "Swimming Women's 4 x 100 metres Freestyle Relay"]
文件 URS.xlsx 的 1988 行 Swimming Women's 4 x 100 metres Freestyle Relay 列数据已加 1。
第 839 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1964, "Volleyball Women's Volleyball"]
文件 URS.xlsx 的 1964 行 Volleyball Women's Volleyball 列数据已加 1。
第 840 行的 ['NOC', 'Year', 'Event'] 列的值: ['GUY', 2016, "Athletics Women's 400 metres"]
文件 GUY.xlsx 的 2016 行 Athletics Women's 400 metres 列数据已加 1。
第 841 行的 ['NOC', 'Year', 'Event'] 列的值: ['GUY', 1988, "Cycling Men's Sprint"]
文件 GUY.xlsx 的 1988 行 Cycling Men's Sprint 列数据已加 1。
第 842 行的 ['NOC', 'Year', 'Event'] 列的值: ['NZL', 1956, "Hockey Men's Hockey"]
文件 NZL.xlsx 的 1956 行 Hockey Men's Hockey 列数据已加 1。
第 843 行的 ['NOC', 'Year', 'Event'] 列的值: ['NZL', 1960, "Hockey Men's Hockey"]
文件 NZL.xlsx 的 1960 行 Hockey Men's Hockey 列数据已加 1。
第 844 行的 ['NOC', 'Year', 'Event'] 列的值: ['GEO', 2016, "Athletics Men's Shot Put"]


文件 ROU.xlsx 的 1952 行 Gymnastics Women's Uneven Bars 列数据已加 1。
第 893 行的 ['NOC', 'Year', 'Event'] 列的值: ['ROU', 1952, "Gymnastics Women's Balance Beam"]
文件 ROU.xlsx 的 1952 行 Gymnastics Women's Balance Beam 列数据已加 1。
第 894 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1980, "Wrestling Men's Lightweight, Freestyle"]
文件 URS.xlsx 的 1980 行 Wrestling Men's Lightweight, Freestyle 列数据已加 1。
第 895 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2004, "Cycling Men's Mountainbike, Cross-Country"]
文件 FRA.xlsx 的 2004 行 Cycling Men's Mountainbike, Cross-Country 列数据已加 1。
第 896 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2008, "Cycling Men's Mountainbike, Cross-Country"]
文件 FRA.xlsx 的 2008 行 Cycling Men's Mountainbike, Cross-Country 列数据已加 1。
第 897 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2012, "Cycling Men's Mountainbike, Cross-Country"]
文件 FRA.xlsx 的 2012 行 Cycling Men's Mountainbike, Cross-Country 列数据已加 1。
第 898 行的 ['NOC', 'Year', 'Event'] 列的值: ['FRA', 2016, "Cycling Men's Mountainbike, Cross-Country"]
文件 FRA.xlsx 的 201

文件 KUW.xlsx 的 1984 行 Diving Men's Platform 列数据已加 1。
第 949 行的 ['NOC', 'Year', 'Event'] 列的值: ['JPN', 2004, "Athletics Men's Marathon"]
文件 JPN.xlsx 的 2004 行 Athletics Men's Marathon 列数据已加 1。
第 950 行的 ['NOC', 'Year', 'Event'] 列的值: ['MEX', 2004, "Judo Men's Extra-Lightweight"]
文件 MEX.xlsx 的 2004 行 Judo Men's Extra-Lightweight 列数据已加 1。
第 951 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1976, "Fencing Men's epee, Individual"]
文件 URS.xlsx 的 1976 行 Fencing Men's epee, Individual 列数据已加 1。
第 952 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1976, "Fencing Men's epee, Team"]
文件 URS.xlsx 的 1976 行 Fencing Men's epee, Team 列数据已加 1。
第 953 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1980, "Fencing Men's epee, Individual"]
文件 URS.xlsx 的 1980 行 Fencing Men's epee, Individual 列数据已加 1。
第 954 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1980, "Fencing Men's epee, Team"]
文件 URS.xlsx 的 1980 行 Fencing Men's epee, Team 列数据已加 1。
第 955 行的 ['NOC', 'Year', 'Event'] 列的值: ['URS', 1980, "Wrestling Men's Featherweight, Freestyle"]
文件 

KeyboardInterrupt: 